# ---
# kind: Service
# apiVersion: v1
# metadata:
#   name: nginx
#   namespace: prod
# spec:
#   ports:  
#     - port: 80
#       targetPort: 80
#   selector:
#     role: nginx

---
kind: ReplicationController
apiVersion: v1
metadata:
  name: nginx
  namespace: prod
spec:
  replicas: 1
  template: 
    metadata: 
      labels:
        role: nginx
    spec:
      containers:
        - name: nginx
          imagePullPolicy: Always
          image: nginx
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: config
          configMap:
            name: nginx

