# ---
# kind: Service
# apiVersion: v1
# metadata:
#   name: python-app-2
#   namespace: prod
# spec:
#   ports:  
#     - port: 80
#       targetPort: 5000
#   selector:
#     role: python-app-2

---
kind: ReplicationController
apiVersion: v1
metadata:
  name: python-app-2
  namespace: prod
spec:
  replicas: 1
  template: 
    metadata: 
      labels:
        role: python-app-2
    spec:
      containers:
        - name: python-app-2
          imagePullPolicy: Always
          image: REPLACEME.dkr.ecr.us-west-2.amazonaws.com/python-app-2:latest
          livenessProbe:   
            httpGet:
              path: /health_check
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 3
          env:
            - name: REDIS_HOST
              value: redis
